repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.238'
    hooks:
      - id: ruff
        args: ['--fix']
  
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    - id: black
      language_version: python3
