name: Build and deploy distribution

on: [push, pull_request]

jobs:
  deploy:
    name: build and deploy to PyPI
    runs-on: "ubuntu-latest"
    permissions:
      id-token: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install build dependencies
        run: python -m pip install build wheel

      - name: Build distributions
        shell: bash -l {0}
        run: |
          git clean -xdf
          pyproject-build

      - name: Publish package to PyPI
        if: github.repository == 'dougiesquire/xbootstrap' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
