name: Test

on: [pull_request, push, workflow_dispatch]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.0

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}
          environment-file: ci/environment-${{ matrix.python-version }}.yml
          activate-environment: xbootstrap-test
          auto-activate-base: false

      - name: Install source
        shell: bash -l {0}
        run: python -m pip install -e .

      - name: List installed packages
        shell: bash -l {0}
        run: conda list

      - name: Run tests
        shell: bash -l {0}
        run: python -m pytest -s .

      - name: Upload code coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
